### ISSUE TITLE
Heads not displaying properly

### ISSUE THREAD

**Issue by meoowe** [CampHQmc/ServerChatHeads#4]
@CamperSamu I just installed the mod onto my fabric 1.20.4 server. I use styled chat for chat formatting and in the config file I use the %chatheads:player% placeholder when a player sends a message.
```
 "chat": "%chatheads:player% <green>${player}</green> : ${message}",
``` 
When I send a message, it looks like this
![Screenshot 2024-01-01 214905](https://github.com/CampHQmc/ServerChatHeads/assets/96916064/a7f841ce-5726-48ea-a6df-80ebb6b9773c)

Instead of a combined head

**Comment by CamperSamu** [comment]
You need to generate a resource pack with Polymer (`/polymer generate resources`) and apply it.

You can also use Polymer Auto-Host to automatically generate and host the resource pack for you (`config/polymer/auto-host.json`, install Polymer if the config is not there).

I should add this to the README + adding a log message when autohost isnt't enabled.

**Comment by meoowe** [comment]
thanks!

**Comment by CamperSamu** [comment]
Embedded Polymer AutoHost and added a warn to enable it if disabled.
Also added a reference to the Polymer Wiki on the README.

**Comment by SnoopyCodeX** [comment]
I have a similar problem but only on bedrock, it works properly on Java version. I have already turned on polymer and also have turned on polymer's autohost. The bedrock version doesn't seem to be able to download the resource pack

**Comment by CamperSamu** [comment]
Bedrock is not supported since it doesn't allow for this kinds of hacks to work.
Also neither Polymer nor ServerChatHeads support bedrock clients or bedrock resource pack conversion.
